---
version: '3'

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
  application_data:
    driver: local

services:
  influxdb:
    image: influxdb:2.7.5-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
    restart: unless-stopped
    env_file:
      - .env_influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    env_file:
      - .env_grafana

  application:
    image: grafana/grafana:latest
    container_name: application
    ports:
      - "8080:8080"
    volumes:
      - application_data
    restart: unless-stopped
